<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-2KH202OE" failures="1" tests="6" name="Test" time="131.893" errors="0" timestamp="2025-09-11T10:22:07 IST">
  <testcase classname="testScript.LoginTest" name="verifyLoginWithValidCredentials" time="8.446">
    <skipped/>
  </testcase> <!-- verifyLoginWithValidCredentials -->
  <testcase classname="testScript.LoginTest" name="verifyLoginWithValidCredentials" time="0.843">
    <skipped/>
  </testcase> <!-- verifyLoginWithValidCredentials -->
  <testcase classname="testScript.LoginTest" name="verifyLoginWithValidCredentials" time="0.859">
    <failure type="java.lang.AssertionError" message="Login is not successful with valid credentials. expected [https://groceryapp.uniqassosiates.com/admin] but found [https://groceryapp.uniqassosiates.com/admin/login]">
      <![CDATA[java.lang.AssertionError: Login is not successful with valid credentials. expected [https://groceryapp.uniqassosiates.com/admin] but found [https://groceryapp.uniqassosiates.com/admin/login]
at testScript.LoginTest.verifyLoginWithValidCredentials(LoginTest.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginWithValidCredentials -->
  <testcase classname="testScript.LoginTest" name="verifyLoginWithInvalidUsername" time="1.14"/>
  <testcase classname="testScript.LoginTest" name="verifyLoginWithInvalidPassword" time="1.326"/>
  <testcase classname="testScript.LoginTest" name="verifyLoginWithInvalidUsernamePassword" time="1.405"/>
</testsuite> <!-- Test -->
